AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Finds advertiser balances and sends off message to sqs queue to process the charge
Parameters:
  MongoUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/db/mongo_uri'
Resources:
  ComputeAdvertiserTransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events: 
        UABSchedule:
          Properties:
            Description: Every week
            Enabled: true
            Name: ComputeAdvertiserTransactionsSchedule
            Schedule: rate(7 days)
          Type: Schedule
      Timeout: 180
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      Policies:
        - AmazonSQSFullAccess
        - Statement:
          - Effect: Allow
            Action:
              - 'kms:Decrypt'
              - 'kms:ListKeys'
            Resource: '*'
      Environment:
        Variables:
          MONGO_URI: !Ref MongoUri
